### ISSUE TITLE
There's an error video player

### ISSUE THREAD

**Issue by AryxDeNub** [balvinderz/animewatcher#16]
**Describe the bug**
There's an error in the video player since in you updated the app 19 days ago.
Most of the episodes work fine but there are certain episodes that don't load.
Such as the 12th episode of Peter Grill (Uncensored)
[https://streamani.net/streaming.php?id=MTQ1OTI0&title=Peter+Grill+to+Kenja+no+Jikan+%28Uncensored%29+Episode+12](https://streamani.net/streaming.php?id=MTQ1OTI0&title=Peter+Grill+to+Kenja+no+Jikan+%28Uncensored%29+Episode+12)
Log gives me the following error.

**2021-07-08 11:05:29.798 20005-20244/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:311)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:939)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-07-08 11:05:29.798 20005-20005/exoerror: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
2021-07-08 11:05:29.799 20005-20160/currentPlaying: https://gogoanime.pe/peter-grill-to-kenja-no-jikan-uncensored-episode-12
2021-07-08 11:05:31.237 20005-20160/vidcdn: vidcdn is https://streamani.net/streaming.php?id=MTQ1OTI0&title=Peter+Grill+to+Kenja+no+Jikan+%28Uncensored%29+Episode+12
2021-07-08 11:05:31.264 20005-20160/gogoanimeerror: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.**

**Comment by Grid-4** [comment]
my video also won't load or playing.need to know why.?
