### ISSUE TITLE
crash when click "watch" if in the episode option we type 0 number

### ISSUE THREAD

**Issue by muhammadarif1** [balvinderz/animewatcher#5]
#### DESCRIBE BUG
 when a user wants to watch an episode of an anime, the user just needs to write the episodes number they want to watch, but if the user writes the number "0" and presses the watch button this application crashes
### STEP TO REPRODUCE
-  open the app 
- click on dub or sub optiont 
- click on search icon and search any anime you want to watch
- then chose an anime
- then in episode option type number"0" and click watch
- see error
#### EXPECTED BEHAVIOR
this application will display an error dialog if the user incorrectly wrote the episodes number

device : oppo neo7
os        : android 6.0
#### BUG RECORDING
https://youtu.be/gvctK4BzNYI
 
LOG CAT

```FATAL EXCEPTION: main
Process: com.stuffbox.webscraper, PID: 29335
java.lang.ArrayIndexOutOfBoundsException: length=135; index=-1
	at java.util.ArrayList.get(ArrayList.java:310)
	at com.stuffbox.webscraper.selectEpisode$3.onClick(selectEpisode.java:116)
	at android.view.View.performClick(View.java:4848)
	at android.view.View$PerformClick.run(View.java:20299)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)```

**Comment by balvinderz** [comment]
fixed it . You can download the new apk now.

**Comment by muhammadarif1** [comment]
thank you, it work as well now

**Comment by balvinderz** [comment]
welcome :)
